# $Id: Makefile,v 1.8 2004/03/12 22:16:59 max Exp $
# $FreeBSD$

LIB=		parser
DESTDIR=
LIBDIR=		.
MAN=
SRCS=		bnep.c cmtp.c hidp.c l2cap.c rfcomm.c hci.c parser.c sdp.c
WARNS?=		2
DEBUG_FLAGS=	-g
CFLAGS=		-O2

NOPROFILE=	1

.include <bsd.lib.mk>

